/* ANifacesLookupComponentSoapBindingProxy.h
   Generated by gSOAP 2.7.9e from ANifaces.h
   Copyright(C) 2000-2006, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef ANifacesLookupComponentSoapBinding_H
#define ANifacesLookupComponentSoapBinding_H
#include "ANifacesH.h"
extern SOAP_NMAC struct Namespace ANifaces_namespaces[];

namespace ANifaces {
class LookupComponentSoapBinding
{   public:
	struct soap *soap;
	const char *endpoint;
	LookupComponentSoapBinding() { soap = soap_new(); if (soap) soap->namespaces = ANifaces_namespaces; endpoint = "http://localhost:8180/ACSFC/services/LookupComponent"; };
	virtual ~LookupComponentSoapBinding() { if (soap) { soap_destroy(soap); soap_end(soap); soap_free(soap); } };
	virtual int ns7__lookupURI(std::string _nameToResolve, std::string &_lookupURIReturn) { return soap ? soap_call_ns7__lookupURI(soap, endpoint, NULL, _nameToResolve, _lookupURIReturn) : SOAP_EOM; };
};

} // namespace ANifaces

#endif
