/* soapH.h
   Generated by gSOAP 2.7.9e from ANifaces.h
   Copyright(C) 2000-2006, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_container_id_forward(struct soap*, const char*, void*, size_t, int, int, size_t, unsigned int);

SOAP_FMAC3 void SOAP_FMAC4 soap_container_insert(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (2)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_time
#define SOAP_TYPE_time (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_time(struct soap*, time_t *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_time(struct soap*, const time_t *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_time(struct soap*, const char*, int, const time_t *, const char*);
SOAP_FMAC3 time_t * SOAP_FMAC4 soap_get_time(struct soap*, time_t *, const char*, const char*);
SOAP_FMAC3 time_t * SOAP_FMAC4 soap_in_time(struct soap*, const char*, time_t *, const char*);

#ifndef SOAP_TYPE__ns7__ACSException
#define SOAP_TYPE__ns7__ACSException (22)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns7__ACSException(struct soap*, const char*, int, const _ns7__ACSException *, const char*);
SOAP_FMAC3 _ns7__ACSException * SOAP_FMAC4 soap_get__ns7__ACSException(struct soap*, _ns7__ACSException *, const char*, const char*);
SOAP_FMAC3 _ns7__ACSException * SOAP_FMAC4 soap_in__ns7__ACSException(struct soap*, const char*, _ns7__ACSException *, const char*);
SOAP_FMAC5 _ns7__ACSException * SOAP_FMAC6 soap_new__ns7__ACSException(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns7__ACSException(struct soap*, _ns7__ACSException*);
SOAP_FMAC3 _ns7__ACSException * SOAP_FMAC4 soap_instantiate__ns7__ACSException(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns7__ACSException(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__ACSException
#define SOAP_TYPE__ns1__ACSException (20)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__ACSException(struct soap*, const char*, int, const _ns1__ACSException *, const char*);
SOAP_FMAC3 _ns1__ACSException * SOAP_FMAC4 soap_get__ns1__ACSException(struct soap*, _ns1__ACSException *, const char*, const char*);
SOAP_FMAC3 _ns1__ACSException * SOAP_FMAC4 soap_in__ns1__ACSException(struct soap*, const char*, _ns1__ACSException *, const char*);
SOAP_FMAC5 _ns1__ACSException * SOAP_FMAC6 soap_new__ns1__ACSException(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__ACSException(struct soap*, _ns1__ACSException*);
SOAP_FMAC3 _ns1__ACSException * SOAP_FMAC4 soap_instantiate__ns1__ACSException(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__ACSException(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__WSANTrigger
#define SOAP_TYPE_ns2__WSANTrigger (16)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__WSANTrigger(struct soap*, const char*, int, const ns2__WSANTrigger *, const char*);
SOAP_FMAC3 ns2__WSANTrigger * SOAP_FMAC4 soap_get_ns2__WSANTrigger(struct soap*, ns2__WSANTrigger *, const char*, const char*);
SOAP_FMAC3 ns2__WSANTrigger * SOAP_FMAC4 soap_in_ns2__WSANTrigger(struct soap*, const char*, ns2__WSANTrigger *, const char*);
SOAP_FMAC5 ns2__WSANTrigger * SOAP_FMAC6 soap_new_ns2__WSANTrigger(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns2__WSANTrigger(struct soap*, ns2__WSANTrigger*);
SOAP_FMAC3 ns2__WSANTrigger * SOAP_FMAC4 soap_instantiate_ns2__WSANTrigger(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__WSANTrigger(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ArrayOf_USCOREsoapenc_USCOREstring
#define SOAP_TYPE_ArrayOf_USCOREsoapenc_USCOREstring (15)
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ArrayOf_USCOREsoapenc_USCOREstring(struct soap*, const char*, int, const ArrayOf_USCOREsoapenc_USCOREstring *, const char*);
SOAP_FMAC3 ArrayOf_USCOREsoapenc_USCOREstring * SOAP_FMAC4 soap_get_ArrayOf_USCOREsoapenc_USCOREstring(struct soap*, ArrayOf_USCOREsoapenc_USCOREstring *, const char*, const char*);
SOAP_FMAC3 ArrayOf_USCOREsoapenc_USCOREstring * SOAP_FMAC4 soap_in_ArrayOf_USCOREsoapenc_USCOREstring(struct soap*, const char*, ArrayOf_USCOREsoapenc_USCOREstring *, const char*);
SOAP_FMAC5 ArrayOf_USCOREsoapenc_USCOREstring * SOAP_FMAC6 soap_new_ArrayOf_USCOREsoapenc_USCOREstring(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ArrayOf_USCOREsoapenc_USCOREstring(struct soap*, ArrayOf_USCOREsoapenc_USCOREstring*);
SOAP_FMAC3 ArrayOf_USCOREsoapenc_USCOREstring * SOAP_FMAC4 soap_instantiate_ArrayOf_USCOREsoapenc_USCOREstring(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ArrayOf_USCOREsoapenc_USCOREstring(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_std__string
#define SOAP_TYPE_std__string (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__string(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__string(struct soap*, const std::string *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_std__string(struct soap*, const std::string *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__string(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_std__string(struct soap*, std::string *, const char*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_std__string(struct soap*, const char*, std::string*, const char*);
SOAP_FMAC5 std::string * SOAP_FMAC6 soap_new_std__string(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_std__string(struct soap*, std::string*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_instantiate_std__string(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__string
#define SOAP_TYPE_xsd__string (13)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__string(struct soap*, const char*, int, const xsd__string *, const char*);
SOAP_FMAC3 xsd__string * SOAP_FMAC4 soap_get_xsd__string(struct soap*, xsd__string *, const char*, const char*);
SOAP_FMAC3 xsd__string * SOAP_FMAC4 soap_in_xsd__string(struct soap*, const char*, xsd__string *, const char*);
SOAP_FMAC5 xsd__string * SOAP_FMAC6 soap_new_xsd__string(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__string(struct soap*, xsd__string*);
SOAP_FMAC3 xsd__string * SOAP_FMAC4 soap_instantiate_xsd__string(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_xsd__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__int
#define SOAP_TYPE_xsd__int (12)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__int(struct soap*, const char*, int, const xsd__int *, const char*);
SOAP_FMAC3 xsd__int * SOAP_FMAC4 soap_get_xsd__int(struct soap*, xsd__int *, const char*, const char*);
SOAP_FMAC3 xsd__int * SOAP_FMAC4 soap_in_xsd__int(struct soap*, const char*, xsd__int *, const char*);
SOAP_FMAC5 xsd__int * SOAP_FMAC6 soap_new_xsd__int(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__int(struct soap*, xsd__int*);
SOAP_FMAC3 xsd__int * SOAP_FMAC4 soap_instantiate_xsd__int(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_xsd__int(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__dateTime
#define SOAP_TYPE_xsd__dateTime (10)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__dateTime(struct soap*, const char*, int, const xsd__dateTime *, const char*);
SOAP_FMAC3 xsd__dateTime * SOAP_FMAC4 soap_get_xsd__dateTime(struct soap*, xsd__dateTime *, const char*, const char*);
SOAP_FMAC3 xsd__dateTime * SOAP_FMAC4 soap_in_xsd__dateTime(struct soap*, const char*, xsd__dateTime *, const char*);
SOAP_FMAC5 xsd__dateTime * SOAP_FMAC6 soap_new_xsd__dateTime(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__dateTime(struct soap*, xsd__dateTime*);
SOAP_FMAC3 xsd__dateTime * SOAP_FMAC4 soap_instantiate_xsd__dateTime(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_xsd__dateTime(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__anyType
#define SOAP_TYPE_xsd__anyType (7)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__anyType(struct soap*, const char*, int, const xsd__anyType *, const char*);
SOAP_FMAC3 xsd__anyType * SOAP_FMAC4 soap_get_xsd__anyType(struct soap*, xsd__anyType *, const char*, const char*);
SOAP_FMAC3 xsd__anyType * SOAP_FMAC4 soap_in_xsd__anyType(struct soap*, const char*, xsd__anyType *, const char*);
SOAP_FMAC5 xsd__anyType * SOAP_FMAC6 soap_new_xsd__anyType(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__anyType(struct soap*, xsd__anyType*);
SOAP_FMAC3 xsd__anyType * SOAP_FMAC4 soap_instantiate_xsd__anyType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_xsd__anyType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Fault * SOAP_FMAC6 soap_new_SOAP_ENV__Fault(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Reason * SOAP_FMAC6 soap_new_SOAP_ENV__Reason(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Code * SOAP_FMAC6 soap_new_SOAP_ENV__Code(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Header * SOAP_FMAC6 soap_new_SOAP_ENV__Header(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE_ns7__lookupURI
#define SOAP_TYPE_ns7__lookupURI (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns7__lookupURI(struct soap*, struct ns7__lookupURI *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns7__lookupURI(struct soap*, const struct ns7__lookupURI *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns7__lookupURI(struct soap*, const struct ns7__lookupURI *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns7__lookupURI(struct soap*, const char*, int, const struct ns7__lookupURI *, const char*);
SOAP_FMAC3 struct ns7__lookupURI * SOAP_FMAC4 soap_get_ns7__lookupURI(struct soap*, struct ns7__lookupURI *, const char*, const char*);
SOAP_FMAC3 struct ns7__lookupURI * SOAP_FMAC4 soap_in_ns7__lookupURI(struct soap*, const char*, struct ns7__lookupURI *, const char*);
SOAP_FMAC5 struct ns7__lookupURI * SOAP_FMAC6 soap_new_ns7__lookupURI(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns7__lookupURI(struct soap*, struct ns7__lookupURI*);
SOAP_FMAC3 struct ns7__lookupURI * SOAP_FMAC4 soap_instantiate_ns7__lookupURI(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns7__lookupURI(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns7__lookupURIResponse
#define SOAP_TYPE_ns7__lookupURIResponse (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns7__lookupURIResponse(struct soap*, struct ns7__lookupURIResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns7__lookupURIResponse(struct soap*, const struct ns7__lookupURIResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns7__lookupURIResponse(struct soap*, const struct ns7__lookupURIResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns7__lookupURIResponse(struct soap*, const char*, int, const struct ns7__lookupURIResponse *, const char*);
SOAP_FMAC3 struct ns7__lookupURIResponse * SOAP_FMAC4 soap_get_ns7__lookupURIResponse(struct soap*, struct ns7__lookupURIResponse *, const char*, const char*);
SOAP_FMAC3 struct ns7__lookupURIResponse * SOAP_FMAC4 soap_in_ns7__lookupURIResponse(struct soap*, const char*, struct ns7__lookupURIResponse *, const char*);
SOAP_FMAC5 struct ns7__lookupURIResponse * SOAP_FMAC6 soap_new_ns7__lookupURIResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns7__lookupURIResponse(struct soap*, struct ns7__lookupURIResponse*);
SOAP_FMAC3 struct ns7__lookupURIResponse * SOAP_FMAC4 soap_instantiate_ns7__lookupURIResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns7__lookupURIResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__unRegister
#define SOAP_TYPE_ns2__unRegister (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__unRegister(struct soap*, struct ns2__unRegister *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__unRegister(struct soap*, const struct ns2__unRegister *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__unRegister(struct soap*, const struct ns2__unRegister *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__unRegister(struct soap*, const char*, int, const struct ns2__unRegister *, const char*);
SOAP_FMAC3 struct ns2__unRegister * SOAP_FMAC4 soap_get_ns2__unRegister(struct soap*, struct ns2__unRegister *, const char*, const char*);
SOAP_FMAC3 struct ns2__unRegister * SOAP_FMAC4 soap_in_ns2__unRegister(struct soap*, const char*, struct ns2__unRegister *, const char*);
SOAP_FMAC5 struct ns2__unRegister * SOAP_FMAC6 soap_new_ns2__unRegister(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns2__unRegister(struct soap*, struct ns2__unRegister*);
SOAP_FMAC3 struct ns2__unRegister * SOAP_FMAC4 soap_instantiate_ns2__unRegister(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__unRegister(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__unRegisterResponse
#define SOAP_TYPE_ns2__unRegisterResponse (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__unRegisterResponse(struct soap*, struct ns2__unRegisterResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__unRegisterResponse(struct soap*, const struct ns2__unRegisterResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__unRegisterResponse(struct soap*, const struct ns2__unRegisterResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__unRegisterResponse(struct soap*, const char*, int, const struct ns2__unRegisterResponse *, const char*);
SOAP_FMAC3 struct ns2__unRegisterResponse * SOAP_FMAC4 soap_get_ns2__unRegisterResponse(struct soap*, struct ns2__unRegisterResponse *, const char*, const char*);
SOAP_FMAC3 struct ns2__unRegisterResponse * SOAP_FMAC4 soap_in_ns2__unRegisterResponse(struct soap*, const char*, struct ns2__unRegisterResponse *, const char*);
SOAP_FMAC5 struct ns2__unRegisterResponse * SOAP_FMAC6 soap_new_ns2__unRegisterResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns2__unRegisterResponse(struct soap*, struct ns2__unRegisterResponse*);
SOAP_FMAC3 struct ns2__unRegisterResponse * SOAP_FMAC4 soap_instantiate_ns2__unRegisterResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__unRegisterResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__register
#define SOAP_TYPE_ns2__register (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__register(struct soap*, struct ns2__register *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__register(struct soap*, const struct ns2__register *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__register(struct soap*, const struct ns2__register *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__register(struct soap*, const char*, int, const struct ns2__register *, const char*);
SOAP_FMAC3 struct ns2__register * SOAP_FMAC4 soap_get_ns2__register(struct soap*, struct ns2__register *, const char*, const char*);
SOAP_FMAC3 struct ns2__register * SOAP_FMAC4 soap_in_ns2__register(struct soap*, const char*, struct ns2__register *, const char*);
SOAP_FMAC5 struct ns2__register * SOAP_FMAC6 soap_new_ns2__register(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns2__register(struct soap*, struct ns2__register*);
SOAP_FMAC3 struct ns2__register * SOAP_FMAC4 soap_instantiate_ns2__register(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__register(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__registerResponse
#define SOAP_TYPE_ns2__registerResponse (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__registerResponse(struct soap*, struct ns2__registerResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__registerResponse(struct soap*, const struct ns2__registerResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__registerResponse(struct soap*, const struct ns2__registerResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__registerResponse(struct soap*, const char*, int, const struct ns2__registerResponse *, const char*);
SOAP_FMAC3 struct ns2__registerResponse * SOAP_FMAC4 soap_get_ns2__registerResponse(struct soap*, struct ns2__registerResponse *, const char*, const char*);
SOAP_FMAC3 struct ns2__registerResponse * SOAP_FMAC4 soap_in_ns2__registerResponse(struct soap*, const char*, struct ns2__registerResponse *, const char*);
SOAP_FMAC5 struct ns2__registerResponse * SOAP_FMAC6 soap_new_ns2__registerResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns2__registerResponse(struct soap*, struct ns2__registerResponse*);
SOAP_FMAC3 struct ns2__registerResponse * SOAP_FMAC4 soap_instantiate_ns2__registerResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__registerResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__sendTrigger
#define SOAP_TYPE_ns2__sendTrigger (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__sendTrigger(struct soap*, struct ns2__sendTrigger *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__sendTrigger(struct soap*, const struct ns2__sendTrigger *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__sendTrigger(struct soap*, const struct ns2__sendTrigger *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__sendTrigger(struct soap*, const char*, int, const struct ns2__sendTrigger *, const char*);
SOAP_FMAC3 struct ns2__sendTrigger * SOAP_FMAC4 soap_get_ns2__sendTrigger(struct soap*, struct ns2__sendTrigger *, const char*, const char*);
SOAP_FMAC3 struct ns2__sendTrigger * SOAP_FMAC4 soap_in_ns2__sendTrigger(struct soap*, const char*, struct ns2__sendTrigger *, const char*);
SOAP_FMAC5 struct ns2__sendTrigger * SOAP_FMAC6 soap_new_ns2__sendTrigger(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns2__sendTrigger(struct soap*, struct ns2__sendTrigger*);
SOAP_FMAC3 struct ns2__sendTrigger * SOAP_FMAC4 soap_instantiate_ns2__sendTrigger(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__sendTrigger(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__sendTriggerResponse
#define SOAP_TYPE_ns2__sendTriggerResponse (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__sendTriggerResponse(struct soap*, struct ns2__sendTriggerResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__sendTriggerResponse(struct soap*, const struct ns2__sendTriggerResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__sendTriggerResponse(struct soap*, const struct ns2__sendTriggerResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__sendTriggerResponse(struct soap*, const char*, int, const struct ns2__sendTriggerResponse *, const char*);
SOAP_FMAC3 struct ns2__sendTriggerResponse * SOAP_FMAC4 soap_get_ns2__sendTriggerResponse(struct soap*, struct ns2__sendTriggerResponse *, const char*, const char*);
SOAP_FMAC3 struct ns2__sendTriggerResponse * SOAP_FMAC4 soap_in_ns2__sendTriggerResponse(struct soap*, const char*, struct ns2__sendTriggerResponse *, const char*);
SOAP_FMAC5 struct ns2__sendTriggerResponse * SOAP_FMAC6 soap_new_ns2__sendTriggerResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns2__sendTriggerResponse(struct soap*, struct ns2__sendTriggerResponse*);
SOAP_FMAC3 struct ns2__sendTriggerResponse * SOAP_FMAC4 soap_instantiate_ns2__sendTriggerResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__sendTriggerResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__unRegisterFE
#define SOAP_TYPE_ns1__unRegisterFE (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__unRegisterFE(struct soap*, struct ns1__unRegisterFE *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__unRegisterFE(struct soap*, const struct ns1__unRegisterFE *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__unRegisterFE(struct soap*, const struct ns1__unRegisterFE *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__unRegisterFE(struct soap*, const char*, int, const struct ns1__unRegisterFE *, const char*);
SOAP_FMAC3 struct ns1__unRegisterFE * SOAP_FMAC4 soap_get_ns1__unRegisterFE(struct soap*, struct ns1__unRegisterFE *, const char*, const char*);
SOAP_FMAC3 struct ns1__unRegisterFE * SOAP_FMAC4 soap_in_ns1__unRegisterFE(struct soap*, const char*, struct ns1__unRegisterFE *, const char*);
SOAP_FMAC5 struct ns1__unRegisterFE * SOAP_FMAC6 soap_new_ns1__unRegisterFE(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__unRegisterFE(struct soap*, struct ns1__unRegisterFE*);
SOAP_FMAC3 struct ns1__unRegisterFE * SOAP_FMAC4 soap_instantiate_ns1__unRegisterFE(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__unRegisterFE(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__unRegisterFEResponse
#define SOAP_TYPE_ns1__unRegisterFEResponse (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__unRegisterFEResponse(struct soap*, struct ns1__unRegisterFEResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__unRegisterFEResponse(struct soap*, const struct ns1__unRegisterFEResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__unRegisterFEResponse(struct soap*, const struct ns1__unRegisterFEResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__unRegisterFEResponse(struct soap*, const char*, int, const struct ns1__unRegisterFEResponse *, const char*);
SOAP_FMAC3 struct ns1__unRegisterFEResponse * SOAP_FMAC4 soap_get_ns1__unRegisterFEResponse(struct soap*, struct ns1__unRegisterFEResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__unRegisterFEResponse * SOAP_FMAC4 soap_in_ns1__unRegisterFEResponse(struct soap*, const char*, struct ns1__unRegisterFEResponse *, const char*);
SOAP_FMAC5 struct ns1__unRegisterFEResponse * SOAP_FMAC6 soap_new_ns1__unRegisterFEResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__unRegisterFEResponse(struct soap*, struct ns1__unRegisterFEResponse*);
SOAP_FMAC3 struct ns1__unRegisterFEResponse * SOAP_FMAC4 soap_instantiate_ns1__unRegisterFEResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__unRegisterFEResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__registerFE
#define SOAP_TYPE_ns1__registerFE (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__registerFE(struct soap*, struct ns1__registerFE *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__registerFE(struct soap*, const struct ns1__registerFE *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__registerFE(struct soap*, const struct ns1__registerFE *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__registerFE(struct soap*, const char*, int, const struct ns1__registerFE *, const char*);
SOAP_FMAC3 struct ns1__registerFE * SOAP_FMAC4 soap_get_ns1__registerFE(struct soap*, struct ns1__registerFE *, const char*, const char*);
SOAP_FMAC3 struct ns1__registerFE * SOAP_FMAC4 soap_in_ns1__registerFE(struct soap*, const char*, struct ns1__registerFE *, const char*);
SOAP_FMAC5 struct ns1__registerFE * SOAP_FMAC6 soap_new_ns1__registerFE(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__registerFE(struct soap*, struct ns1__registerFE*);
SOAP_FMAC3 struct ns1__registerFE * SOAP_FMAC4 soap_instantiate_ns1__registerFE(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__registerFE(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__registerFEResponse
#define SOAP_TYPE_ns1__registerFEResponse (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__registerFEResponse(struct soap*, struct ns1__registerFEResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__registerFEResponse(struct soap*, const struct ns1__registerFEResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__registerFEResponse(struct soap*, const struct ns1__registerFEResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__registerFEResponse(struct soap*, const char*, int, const struct ns1__registerFEResponse *, const char*);
SOAP_FMAC3 struct ns1__registerFEResponse * SOAP_FMAC4 soap_get_ns1__registerFEResponse(struct soap*, struct ns1__registerFEResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__registerFEResponse * SOAP_FMAC4 soap_in_ns1__registerFEResponse(struct soap*, const char*, struct ns1__registerFEResponse *, const char*);
SOAP_FMAC5 struct ns1__registerFEResponse * SOAP_FMAC6 soap_new_ns1__registerFEResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__registerFEResponse(struct soap*, struct ns1__registerFEResponse*);
SOAP_FMAC3 struct ns1__registerFEResponse * SOAP_FMAC4 soap_instantiate_ns1__registerFEResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__registerFEResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Detail * SOAP_FMAC6 soap_new_SOAP_ENV__Detail(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (56)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_PointerTons2__WSANTrigger
#define SOAP_TYPE_PointerTons2__WSANTrigger (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__WSANTrigger(struct soap*, ns2__WSANTrigger *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__WSANTrigger(struct soap*, ns2__WSANTrigger *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__WSANTrigger(struct soap*, const char *, int, ns2__WSANTrigger *const*, const char *);
SOAP_FMAC3 ns2__WSANTrigger ** SOAP_FMAC4 soap_get_PointerTons2__WSANTrigger(struct soap*, ns2__WSANTrigger **, const char*, const char*);
SOAP_FMAC3 ns2__WSANTrigger ** SOAP_FMAC4 soap_in_PointerTons2__WSANTrigger(struct soap*, const char*, ns2__WSANTrigger **, const char*);

#ifndef SOAP_TYPE_PointerToArrayOf_USCOREsoapenc_USCOREstring
#define SOAP_TYPE_PointerToArrayOf_USCOREsoapenc_USCOREstring (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToArrayOf_USCOREsoapenc_USCOREstring(struct soap*, ArrayOf_USCOREsoapenc_USCOREstring *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToArrayOf_USCOREsoapenc_USCOREstring(struct soap*, ArrayOf_USCOREsoapenc_USCOREstring *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToArrayOf_USCOREsoapenc_USCOREstring(struct soap*, const char *, int, ArrayOf_USCOREsoapenc_USCOREstring *const*, const char *);
SOAP_FMAC3 ArrayOf_USCOREsoapenc_USCOREstring ** SOAP_FMAC4 soap_get_PointerToArrayOf_USCOREsoapenc_USCOREstring(struct soap*, ArrayOf_USCOREsoapenc_USCOREstring **, const char*, const char*);
SOAP_FMAC3 ArrayOf_USCOREsoapenc_USCOREstring ** SOAP_FMAC4 soap_in_PointerToArrayOf_USCOREsoapenc_USCOREstring(struct soap*, const char*, ArrayOf_USCOREsoapenc_USCOREstring **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns7__ACSException
#define SOAP_TYPE_PointerTo_ns7__ACSException (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns7__ACSException(struct soap*, _ns7__ACSException *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns7__ACSException(struct soap*, _ns7__ACSException *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns7__ACSException(struct soap*, const char *, int, _ns7__ACSException *const*, const char *);
SOAP_FMAC3 _ns7__ACSException ** SOAP_FMAC4 soap_get_PointerTo_ns7__ACSException(struct soap*, _ns7__ACSException **, const char*, const char*);
SOAP_FMAC3 _ns7__ACSException ** SOAP_FMAC4 soap_in_PointerTo_ns7__ACSException(struct soap*, const char*, _ns7__ACSException **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__ACSException
#define SOAP_TYPE_PointerTo_ns1__ACSException (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__ACSException(struct soap*, _ns1__ACSException *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__ACSException(struct soap*, _ns1__ACSException *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__ACSException(struct soap*, const char *, int, _ns1__ACSException *const*, const char *);
SOAP_FMAC3 _ns1__ACSException ** SOAP_FMAC4 soap_get_PointerTo_ns1__ACSException(struct soap*, _ns1__ACSException **, const char*, const char*);
SOAP_FMAC3 _ns1__ACSException ** SOAP_FMAC4 soap_in_PointerTo_ns1__ACSException(struct soap*, const char*, _ns1__ACSException **, const char*);

#ifndef SOAP_TYPE_PointerToxsd__anyType
#define SOAP_TYPE_PointerToxsd__anyType (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToxsd__anyType(struct soap*, xsd__anyType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToxsd__anyType(struct soap*, xsd__anyType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToxsd__anyType(struct soap*, const char *, int, xsd__anyType *const*, const char *);
SOAP_FMAC3 xsd__anyType ** SOAP_FMAC4 soap_get_PointerToxsd__anyType(struct soap*, xsd__anyType **, const char*, const char*);
SOAP_FMAC3 xsd__anyType ** SOAP_FMAC4 soap_in_PointerToxsd__anyType(struct soap*, const char*, xsd__anyType **, const char*);

#ifndef SOAP_TYPE_PointerToPointerTostd__string
#define SOAP_TYPE_PointerToPointerTostd__string (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToPointerTostd__string(struct soap*, std::string **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToPointerTostd__string(struct soap*, std::string **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToPointerTostd__string(struct soap*, const char *, int, std::string **const*, const char *);
SOAP_FMAC3 std::string *** SOAP_FMAC4 soap_get_PointerToPointerTostd__string(struct soap*, std::string ***, const char*, const char*);
SOAP_FMAC3 std::string *** SOAP_FMAC4 soap_in_PointerToPointerTostd__string(struct soap*, const char*, std::string ***, const char*);

#ifndef SOAP_TYPE_PointerTostd__string
#define SOAP_TYPE_PointerTostd__string (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostd__string(struct soap*, std::string *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostd__string(struct soap*, std::string *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostd__string(struct soap*, const char *, int, std::string *const*, const char *);
SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_get_PointerTostd__string(struct soap*, std::string **, const char*, const char*);
SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_in_PointerTostd__string(struct soap*, const char*, std::string **, const char*);

#ifndef SOAP_TYPE_PointerTotime
#define SOAP_TYPE_PointerTotime (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotime(struct soap*, time_t *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotime(struct soap*, time_t *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotime(struct soap*, const char *, int, time_t *const*, const char *);
SOAP_FMAC3 time_t ** SOAP_FMAC4 soap_get_PointerTotime(struct soap*, time_t **, const char*, const char*);
SOAP_FMAC3 time_t ** SOAP_FMAC4 soap_in_PointerTotime(struct soap*, const char*, time_t **, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#endif

/* End of soapH.h */
