/* soapRegistrationComponentSoapBindingProxy.h
   Generated by gSOAP 2.7.9e from ANifaces.h
   Copyright(C) 2000-2006, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapRegistrationComponentSoapBinding_H
#define soapRegistrationComponentSoapBinding_H
#include "soapH.h"
class RegistrationComponentSoapBinding
{   public:
	struct soap *soap;
	const char *endpoint;
	RegistrationComponentSoapBinding()
	{ soap = soap_new(); endpoint = "http://localhost:8180/ACSFC/services/RegistrationComponent"; if (soap && !soap->namespaces) { static const struct Namespace namespaces[] = 
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns1", "http://registrationcomponent", NULL, NULL},
	{"ns2", "urn:trg_producer", NULL, NULL},
	{"ns7", "http://lookupcomponent", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap->namespaces = namespaces; } };
	virtual ~RegistrationComponentSoapBinding() { if (soap) { soap_destroy(soap); soap_end(soap); soap_free(soap); } };
	virtual int ns1__registerFE(std::string _feName, std::string _feDescription, ArrayOf_USCOREsoapenc_USCOREstring *_sapId, ArrayOf_USCOREsoapenc_USCOREstring *_strLocation, ArrayOf_USCOREsoapenc_USCOREstring *_sapDescription, struct ns1__registerFEResponse &_param_1) { return soap ? soap_call_ns1__registerFE(soap, endpoint, NULL, _feName, _feDescription, _sapId, _strLocation, _sapDescription, _param_1) : SOAP_EOM; };
	virtual int ns1__unRegisterFE(std::string _feName, struct ns1__unRegisterFEResponse &_param_2) { return soap ? soap_call_ns1__unRegisterFE(soap, endpoint, NULL, _feName, _param_2) : SOAP_EOM; };
};
#endif
