/* soaptrg_USCOREproducerProxy.h
   Generated by gSOAP 2.7.9e from ANifaces.h
   Copyright(C) 2000-2006, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soaptrg_USCOREproducer_H
#define soaptrg_USCOREproducer_H
#include "soapH.h"
class trg_USCOREproducer
{   public:
	struct soap *soap;
	const char *endpoint;
	trg_USCOREproducer()
	{ soap = soap_new(); endpoint = "http://localhost:8020"; if (soap && !soap->namespaces) { static const struct Namespace namespaces[] = 
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns1", "http://registrationcomponent", NULL, NULL},
	{"ns2", "urn:trg_producer", NULL, NULL},
	{"ns7", "http://lookupcomponent", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap->namespaces = namespaces; } };
	virtual ~trg_USCOREproducer() { if (soap) { soap_destroy(soap); soap_end(soap); soap_free(soap); } };
	virtual int ns2__sendTrigger(ns2__WSANTrigger *trigger, std::string &result) { return soap ? soap_call_ns2__sendTrigger(soap, endpoint, NULL, trigger, result) : SOAP_EOM; };
	virtual int ns2__register(int id, std::string &result) { return soap ? soap_call_ns2__register(soap, endpoint, NULL, id, result) : SOAP_EOM; };
	virtual int ns2__unRegister(int id, std::string &result) { return soap ? soap_call_ns2__unRegister(soap, endpoint, NULL, id, result) : SOAP_EOM; };
};
#endif
